# docker-compose.yaml
version: "3"
services:
  tr069-simulator:
    container_name: stun-client
    image: stun-client:1.0.0
    network_mode: host
#    sysctls:
#      net.ipv4.ip_local_port_range: "10000 65000"
    cap_add:
      - SYS_PTRACE
    environment:
      LOG_LEVEL: info
      DEVICE_NUMBER: 50000
      STUN_ENABLED: true
      STUN_HOST: 127.0.0.1
      STUN_PORT: 3478
      STUN_USERNAME: ""
      STUN_PASSWORD: ""
      STUN_HEARTBEAT_INTERVAL: 5
      STUN_THREAD: 64
      JAVA_OPTS: >-
        -Xmx600M
        -Xms600M
        -Xmn200M
        -XX:MaxMetaspaceSize=100M
        -XX:MetaspaceSize=100M
        -XX:+UseG1GC
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
