# docker-compose.yaml
version: "3"
services:
  tr069-simulator:
    container_name: stun-client
    image: stun-client:1.0.0
    network_mode: host
#    sysctls:
#      net.ipv4.ip_local_port_range: "10000 65000"
    cap_add:
      - SYS_PTRACE
    environment:
      LOG_LEVEL: debug
      DEVICE_NUMBER: 200000
      QUEUE_CAPACITY: 1000000
      NETTY_THREAD: 128
      BOOT_THREAD: 32
      STUN_ENABLED: true
      STUN_HOST: 127.0.0.1
      STUN_PORT: 3478
      STUN_USERNAME: ""
      STUN_PASSWORD: ""
      STUN_HEARTBEAT_INTERVAL: 1
      STUN_THREAD: 16
      JAVA_OPTS: >-
        -Xmx6G
        -Xms6G
        -Xmn2G
        -XX:MaxMetaspaceSize=300M
        -XX:MetaspaceSize=300M
        -XX:+UseG1GC
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
