spring:
  application:
    name: stun-client-simulator
server:
  port: 8060
logging:
  level:
    io.change.stun: ${LOG_LEVEL:info}
simulator:
  device_number: ${DEVICE_NUMBER:50000}
  netty_thread: ${NETTY_THREAD:128}
  stun:
    host: ${STUN_HOST:127.0.0.1}
    port: ${STUN_PORT:3478}
    username: ${STUN_USERNAME:""}
    password: ${STUN_PASSWORD:""}
    heartbeatInterval: ${STUN_HEARTBEAT_INTERVAL:30}
    thread: ${STUN_THREAD:16}




